### ISSUE TITLE
Dot Code School Suggestion: Feedback for Section 1 - Chapter 3: Substrate Storage

### ISSUE THREAD

**Issue by benjaminsalon** [shawntabrizi/polkadot-sdk-tutorial-dex#1]
Hey @philoniare, I think this part about the ValueQuery is not true: 

https://github.com/philoniare/polkadot-sdk-tutorial-dex/blob/b4611fc2ec6dbae147f15f46e05d0db99778e6ed/README.md?plain=1#L22

The ValueQuery is there to define the default behavior of the storage when we try to `get` something with an unexisting key. You can check here: https://paritytech.github.io/polkadot-sdk/master/frame_support/storage/types/trait.QueryKindTrait.html

**Comment by shawntabrizi** [comment]
yes, this is correct.

The way i would explain value query is to go a little deeper in general:

- in a DB, storage is always an option: there is either `Some` value at a key, or there is `None` value at a key.
- the default behavior for accessing storage is `OptionQuery` which exposes exactly that information to you the developer
- there are scenarios where you want `None` to actually represent some value, the common example is `Balance` where `None` is exactly the same as having `0` balance. In this case, you would probably rather handle `0` than an option each time you query and use a balance.
- value query will return the default value for a type when the value is `None` and can be used in scenarios like this.
- to adjust the value returned by value query, you can also adjust the `defaultvalue` parameter or whatevr it is called

**Comment by philoniare** [comment]
@benjaminsalon @shawntabrizi Thanks for pointing it out guys. Updated
